### PR TITLE
Fixed missing semicolon which causes IE11 to crash

### PR DESCRIPTION
**Pull request by JanLoebel**
I had to fix a missing semicolon, which in my angular project lead to a crash in IE11 which complained about that missing semicolon.

### CODE REVIEW

**Review by johachi — APPROVED** [review]
IE11 is strange :P

**Comment by JanLoebel** [comment]
Indeed!

**Comment by JanLoebel** [comment]
Any chances that there will be a new release 2.0.2 soon? I'm using leaflet-lasso which is using your project, so I will have to create a new pull request there also whenever the fix is available :)

**Comment by johachi** [comment]
@JanLoebel , I will to that update now!

**Pull request merged**
