### PR TITLE
Correcting spelling mistake in validateCenter.js

### PR DESCRIPTION
**Pull request by kallewesterling**
Spelling mistake

### CODE REVIEW

**Review by johachi — APPROVED** [review]
Thank you! How did you discover this? Did you get the error?

**Comment by kallewesterling** [comment]
Yes! I am creating a data visualization using the GeoLayers 3 plugin for After Effects and I needed something that could generate nice little polygons to make the dataset easier for it to handle. Your package made all the difference!

**Comment by johachi** [comment]
> Yes! I am creating a data visualization using the GeoLayers 3 plugin for After Effects and I needed something that could generate nice little polygons to make the dataset easier for it to handle. Your package made all the difference!

That is great to hear! Thank you.

Btw, it seems like the tests weren't updated. Could you please do that as well?

**Comment by kallewesterling** [comment]
Done!

**Comment by johachi** [comment]
Thank you for you contribution @kallewesterling!

**Pull request merged**
