### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by johachi**
I liked this project, so I decided to try and add some tests to it.

If i get this merged, I might also add the feature of getting the polygon drawn clockwise (since it coordinates of inner polygons (holes) has to be clockwise, but the outer polygon has to be counter-clockwise.

I might also add test for non-trivial center positions.

This tests the following:
**Input validation**
- [x] Throw error on in-valid longitude argument (types and value)
- [x] Throw error on in-valid latitude argument (types and value)
- [x] Throw error on in-valid center argument (types and values)
- [x] Throw error on in-valid radius (types and value, min is set to >0 m)
- [x] Throw error on invalid segment arguments (type and value, min set to 3)

**Output validation**
- [x] Polygon has the correct attributes
- [x] All attributes has correct type and length (for arrays)

Trivial center positions: 
- [x] Center is east of GMT, north of equator
- [x] Center is east of GMT, south of equator
- [x] Center is west of GMT, north of equator
- [x] Center is west of GMT, south of equator
- [x] Center is on [0, 0]
- [x] Pentagon on pentagon test (this one is just for fun)

Non-trivial center positions (not implemented):
- Positions on the lat -90
- Positions on the lat 90
- Positions on the lng -180
- Positions on the lng 180
- Circle border passes the 180th Meridian
- Circle area includes north pole
- Circle area includes south pole

Edit: Change min radius to >0m to not be a breaking change (previously set to >=1).

### CODE REVIEW

**Comment by johachi** [comment]
I forgot to add, I'm using Prettify, and prettified the files.

I will happily change my code if you follow some other code style (but even happier if you accept prettified code :) )

**Comment by gabzim** [comment]
Happy to merge this if you can fix the conflict!

**Comment by johachi** [comment]
@gabzim I just solved the merge conflict, please have a look!

**Comment by johachi** [comment]
~~@gabzim , pleasewait a sec with merging this, I need to fix the behavior when numberOfSegments is undefined.~~

Edit: Above has been fixed.

**Review by gabzim — APPROVED** [review]

**Pull request merged**
